// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5rk_epkhih6ittAEGTRUy_XsdnWGH0ck',
    appId: '1:70428585714:web:23ccdb8ecaf89d1b7e6a6b',
    messagingSenderId: '70428585714',
    projectId: 'myproject-74a33',
    authDomain: 'myproject-74a33.firebaseapp.com',
    databaseURL: 'https://myproject-74a33-default-rtdb.firebaseio.com',
    storageBucket: 'myproject-74a33.appspot.com',
    measurementId: 'G-EJQBKBJ0SY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1CKt3-I8VCOdLOdGzhIMSRmATJUjA1A4',
    appId: '1:70428585714:android:cc1cd07cd49bd7e97e6a6b',
    messagingSenderId: '70428585714',
    projectId: 'myproject-74a33',
    databaseURL: 'https://myproject-74a33-default-rtdb.firebaseio.com',
    storageBucket: 'myproject-74a33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ2gkB0O5Or_8ljgxZh_udzUpByTf8MiQ',
    appId: '1:70428585714:ios:a05f9295810a9d1f7e6a6b',
    messagingSenderId: '70428585714',
    projectId: 'myproject-74a33',
    databaseURL: 'https://myproject-74a33-default-rtdb.firebaseio.com',
    storageBucket: 'myproject-74a33.appspot.com',
    iosClientId: '70428585714-ss4b2c9jcmpp3qoac654tj7npr95ucge.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ2gkB0O5Or_8ljgxZh_udzUpByTf8MiQ',
    appId: '1:70428585714:ios:d1b472597483df597e6a6b',
    messagingSenderId: '70428585714',
    projectId: 'myproject-74a33',
    databaseURL: 'https://myproject-74a33-default-rtdb.firebaseio.com',
    storageBucket: 'myproject-74a33.appspot.com',
    iosClientId: '70428585714-9o48rtf4j1r161fvo0eqhj2l44cop8il.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryApp.RunnerTests',
  );
}
